on:
  push:
    branches:
      - main
    paths:
      - "src/*"
      - ".github/workflows/DeployServer.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test workflow
        run: echo "YAY this workflow is running"
      - name: Add github username
        run: git config --global user.name 'shainasm'
      - name: Add github email
        run: git config --global user.email 'smulani2002@gmail.com@gmail.com'
      - name: add heroku remote
        run: git remote add heroku https://heroku:960d255c-dc7b-4bd8-8db3-d251bef3c2a0@git.heroku.com/shaina-recipe-api.git
      - name: Fetch repo
        run: git fetch --unshallow
      - name: push to heroku remote
        run: git push heroku main --force